[package]
name = "p2pllm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hdfs = "0.0.4"
structopt = { version = "0.3", default-features = false }
libp2p = "0.42.0"
tch = "0.6.0"
